name: flutter_car_installmant_calculation
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2 #แพ็คเกจที่ช่วยในการเปิดกล้ออง เปิดแกลอรี่
  intl: ^0.20.2 #แพ็คเกจที่ช่วยในการจัดรูปแบบข้อความ ตัวเลข วันที่
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
    - assets/images/
